version: '3.8'

services:
  wikipedia-converter-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wikipedia-to-markdown-dev
    ports:
      - "7861:7861"
    environment:
      - PYTHONUNBUFFERED=1
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7861
    volumes:
      # 開発時にコードの変更をリアルタイムで反映
      - .:/app
      - /app/__pycache__
    restart: unless-stopped
    command: python app.py
    networks:
      - wikipedia-dev-network

networks:
  wikipedia-dev-network:
    driver: bridge