name: Sync to Hugging Face

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Git設定
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # Hugging Face Hubにリモートを追加
          git remote add hf https://huggingface.co/spaces/MakiAi/wikipedia-to-markdown
          
          # 強制プッシュでHugging Faceに同期
          git push --force https://user:$HF_TOKEN@huggingface.co/spaces/MakiAi/wikipedia-to-markdown HEAD:main
